### PR TITLE
added support for Homematic Weather station basic and Hörmann Gate Drives

### PR DESCRIPTION
**Pull request by betrino**
I have added support for Homematic Weather station basic (+ updated README and added CLI and Auth script). I have tested it in combination with Mosquitto and OpenHAB and it works good.

Thanks for your great work by the way!

### CODE REVIEW

**Comment by cyraxx** [comment]
Nice, thanks for your contribution! I'll need to spend a little time reviewing the individual things you added to make sure I understand them well, but it looks great so far.

Are you still working on this or is it good to go?

**Comment by betrino** [comment]
Now it is good to go. Could you please review the code?

For my other changes I will create a new feature branch.

**Comment by cyraxx** [comment]
First of all, this is fantastic and adds a lot of new functionality, thank you! And I'm sorry it took me so long to review, the last weeks have been very busy for me.

A couple of remarks from my side:
* I'm not a fan of copying over the `hmip_cli.py` and `hmip_generate_auth_token.py` from homematicip, this creates code duplication. I could see keeping the auth token script in the project to make onboarding easier for new users, but then it should be clearly marked as a duplicate with a reference to where it comes from. Would also need a README update.
* Is it customary for command topics on MQTT to start with `cmd/`? So far I've only seen it the other way around, where the base topic is the same but `/command` is added at the end. But if starting with `cmd/` is a common way to do this then I'm fine with adopt it.
* I'd like to rearrange some things in the README to make it clearer but that's something I'd be happy to handle myself.
* At some point the code should probably be refactored to be more structured (e.g. one class per device type) but I don't see that as necessary just yet.

**Comment by betrino** [comment]
> the last weeks have been very busy for me.

The same here. ;-)

> I'm not a fan of copying over the hmip_cli.py and hmip_generate_auth_token.py

That's fine for me. I have removed this two files.

> Is it customary for command topics on MQTT to start with cmd/?

I searched for best practices for MQTT and found some contradicting information. Finally, I followed Amazon's best practice, see here: https://docs.aws.amazon.com/whitepapers/latest/designing-mqtt-topics-aws-iot-core/mqtt-design-best-practices.html
_When you design MQTT topics for command requests, follow this structure:_
`cmd/<application>/<context>/<destination-id>/<req-type> `

> I'd like to rearrange some things in the README

Yes, please do that. :-)

> At some point the code should probably be refactored to be more structured

I'm aware of that. At the moment the code basis is historically grown as I would have said. ;-) The code works so far, but feel free to refactor when you have time. I also like to contribute afterwards. :-)

**Comment by cyraxx** [comment]
Thank you! I'll deploy it on my own home hub now and give it a test run for a bit 😃 If I don't run into any issues, I'll (finally) merge!

As for the MQTT topics, Tasmota uses a prefix in a similar fashion, whereas Shelly uses a suffix. And if the best practices say prefix too then let's just keep it that way.

**Comment by cyraxx** [comment]
I've had this running for a while on my home setup, everything seems to work fine!

What's weird is that whenever I set the heating group temperature through MQTT, I get this error message:
> ERROR:root:updateHomematicGroup failed: string indices must be integers

However, the update does go through just fine and the new temperature shows up right away in the Homematic IP app.

This looks to me like an issue within the homematicip-rest-api package itself but I haven't started digging deeper into it yet.

**Comment by cyraxx** [comment]
Gosh, it's been over a year... I guess you could say this code has proven itself, so I've gone ahead and merged it.

I've added underscores to a couple of MQTT topic prefixes for consistency. Sorry for breaking your integrations 🙂

**Pull request merged**
